% Shape_Part2, 10/7/24. This script analyses the ear-canal shape functions
% including area function, eccentricity, curvature, and torsion. It reads a
% MAT file with individual ear shape data saved by Shape_Part1. It can
% either read a MAT file in a shared folder matFiles_JASA that was
% generated by the authors of the JASA article, or a MAT file in an
% external-user folder matFiles_External for MAT files written out by the
% external user from running Shape_Part 1.
% Adapted from batchProcessCanal5_JASA, 9/26/2024. 

close all, clear all;

% fnLabelsMAT name is hard-coded in the following if...end statement, 
% but user will navigate in the fnLabelsMAT folder to select a MAT file 
% written by part 1 with volume segmentation.
swNewFolder=0; % User chooses matFiles which folder to use that hold 
% MAT files in part 1 code after volume segmentation.
% 0 for default folder with shared data files or 1 for user folder with
% newly analyzed data files.
if swNewFolder==0 % date/time format YYYYMMDDTHHMMSS
  matFiles=[ mfilename('fullpath') filesep 'matFiles_JASA'];
else
    
end
fnLabelsMAT='';
%fnLabelsMAT='A021_L_004_Dp25_20210719_20240930T165348'; % test ear A in _JASA folder
%fnLabelsMAT='A026_R_002_Dp25_20210818_20241003T125347'; % test ear B
%fnLabelsMAT='A024_L_003_Dp25_'; % test ear C, look in matFiles folder
%fnLabelsMAT='A008_R_003_Dp25_20210521_20241003T133417'; % test ear D
if isempty(fnLabelsMAT)
     [fnLabelsMAT,matFiles] = uigetfile(['..' filesep 'matFiles_JASA' filesep '*.mat'],'Select a .MAT file');
end
% imult=4 with Dp25 or 0.25 mm steps along canal axis in initial processing,
% then steps 1 mm along canal axis in discrete Frenet frame.
ifig=1;
imult = 4;
fnM=fullfile(matFiles,fnLabelsMAT);
% Probably don't need any output here or need to replot major results from
% part 1.
swNewPlot=1; % 1 to replot major results from volume segmentation, or 0 to not replot
%dirESS='\\boystown.org\btnrh\PHAL\ESS';
%SidEar=fnM(1:6);
%fnShape=[fnM(1:6),'_Shp_',datestr(now,29)]; % only by date, not date and time
%if imult~=2
%  fnShape=[fnShape,'_im',int2str(imult)];
%end
swSimpleTitle=1; % default ==0, ==1 to make plots for manuscript
%keyboard

%[ifig,hfShape]=ProcessCanal5_JASA(ifig,imult,fnM,swNewPlot,dirESS,...
%  swSave,fnShape,swSimpleTitle); % swSave is 0 in shared code
[ifig,hfShape]=ProcessCanal5_JASA(ifig,imult,fnM,swNewPlot,[],0,[],...
  swSimpleTitle);


